# Generated by Django 4.0.4 on 2022-05-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_pontuacaoquizz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens')),
                ('ano_de_realizacao', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='pontuacaoquizz',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pontuacaoquizz',
            old_name='pontuacao',
            new_name='points',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('languages', models.ManyToManyField(to='portfolio.language')),
                ('practical_professor', models.ManyToManyField(related_name='courses', to='portfolio.teacher')),
                ('projects', models.ManyToManyField(to='portfolio.project')),
                ('theory_professors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.teacher')),
            ],
        ),
    ]
