# Generated by Django 4.0.4 on 2022-05-28 14:07

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_language_project_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=portfolio.models.resolution_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagem',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
