# Generated by Django 4.0.4 on 2022-05-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='description',
        ),
    ]
