# Generated by Django 4.0.4 on 2022-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_nome_teacher_name_remove_teacher_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ano_de_realizacao',
            new_name='year_made',
        ),
        migrations.RemoveField(
            model_name='project',
            name='imagem',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/'),
            preserve_default=False,
        ),
    ]
