# Generated by Django 4.0.4 on 2022-05-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_descricao_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='description',
        ),
    ]
